FROM fedora:latest
RUN dnf install -y curl gcc
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
WORKDIR /usr/src/app
COPY . .
RUN cargo build --release
ENV RUST_LOG=debug
CMD ["./target/release/demo"]